modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/firstdarkdev/sdlink/issues"

[[mods]]
modId="sdlink"
version="${file.jarVersion}"
displayName="Simple Discord Link"
logoFile="sdlink_logo.png"
authors="HypherionSA"
description='''A simple Minecraft to Discord Chat bot with Whitelisting'''
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.sdlink]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"

[[dependencies.sdlink]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.sdlink]]
modId="craterlib"
mandatory=true
versionRange="[1.0,)"
ordering="AFTER"
side="SERVER"